global:
  smtp_smarthost: 'smtp.qiye.163.com:25'
  smtp_from: 'XX@XX'
  smtp_auth_username: 'XX@XX'
  smtp_auth_password: 'you_password'
  smtp_require_tls: false #不进行tls验证

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10m
  receiver: live-monitoring

receivers:
- name: 'live-monitoring'
  email_configs:
  - to: 'XX@XX' #收邮件的邮箱
