global:
  scrape_interval:     60s
  evaluation_interval: 20s
  scrape_timeout: 15s

rule_files:
  - "node_down.yml"
  - "vmware_exporter.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 192.168.11.252:9093

scrape_configs:
  - job_name: 'web' 
    scrape_interval: 5s
    static_configs: 
      - targets: 
        - localhost:9090
      
  - job_name: 'mysql-Host-monitoring'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - 192.168.11.200:9104

  - job_name: 'Windows-Host-monitoring'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - 192.168.11.63:9182
      
  - job_name: 'Linux-Host-monitoring'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 192.168.11.230:9100
   
  - job_name: 'docker-cadvisor-monitoring'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 192.168.11.230:8082
        
  - job_name: 'Redis-monitoring'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - 192.168.11.253:9121                               
