rule_files:
  - "node_down.yml"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.11.252:9090']
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.11.252:9100']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.11.252:8080']                                    
