{
 "title": "Windows Node",
 "description": "General stats dashboard with node selector, uses metrics from wmi_exporter",
 "tags": [
  "windows",
  "wmi_exporter",
  "prometheus"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "60s" },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(wmi_system_system_up_time, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "repeat": "host",
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "wmi_os_time{instance=~\"$server\"} - wmi_system_system_up_time{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(wmi_cpu_time_total{mode=\"idle\", instance=~\"$server\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(wmi_cs_physical_memory_bytes{instance=~\"$server\"} - wmi_os_physical_memory_free_bytes{instance=~\"$server\"}) / wmi_cs_physical_memory_bytes{instance=~\"$server\"} * 100"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(wmi_logical_disk_size_bytes{volume!~\"Harddisk.*\", instance=\"$server\"}) by (instance) - sum(wmi_logical_disk_free_bytes{volume!~\"Harddisk.*\", instance=\"$server\"}) by (instance)) / sum(wmi_logical_disk_size_bytes{volume!~\"Harddisk.*\", instance=\"$server\"}) by (instance) * 100"
    }
   ]
  },
  {
   "title": "带宽使用率",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(irate(wmi_net_bytes_total{instance=\"$server\"}[1m])) > 1)* 8"
    }
   ]
  },
  {
   "title": "内存详情",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "wmi_cs_physical_memory_bytes{instance=~\"$server\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Physical memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "wmi_os_physical_memory_free_bytes{instance=~\"$server\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Free physical memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "wmi_os_virtual_memory_bytes{instance=~\"$server\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Virtual memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "wmi_os_virtual_memory_free_bytes{instance=~\"$server\"}",
     "legendFormat": "Free virtual memory"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "repeat": "host",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "wmi_cs_logical_processors{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "repeat": "host",
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "wmi_cs_physical_memory_bytes{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "CPU负载（16核）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (mode) (rate(wmi_cpu_time_total{instance=~\"$server\"}[5m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{mode}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg without (cpu) (sum(irate(wmi_cpu_time_total{instance=\"$server\",mode!=\"idle\"}[5m])) by (mode)) / 16)* 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "网络详情",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(wmi_net_bytes_sent_total{instance=~\"$server\",nic=\"Broadcom_NetXtreme_Gigabit_Ethernet\"}[$interval]) >0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Sent-上传",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "- rate(wmi_net_bytes_received_total{instance=~\"$server\",nic=\"Broadcom_NetXtreme_Gigabit_Ethernet\"}[$interval]) <0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Received-下载",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "每小时流量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(wmi_net_bytes_received_total{instance=\"$server\"}[1h])) by (instance)",
     "legendFormat": "Received-下载"
    },
    {
     "expr": "sum(increase(wmi_net_bytes_sent_total{instance=\"$server\"}[1h])) by (instance)",
     "legendFormat": "Sent-上传"
    }
   ]
  },
  {
   "title": "Network discarded/error packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 15 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(wmi_net_packets_outbound_discarded{instance=~\"$server\", nic=\"Broadcom_NetXtreme_Gigabit_Ethernet\"}[$interval]) + irate(wmi_net_packets_outbound_errors{instance=~\"$server\"}[$interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Sent-上传",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(wmi_net_packets_received_discarded{instance=~\"$server\", nic=\"Broadcom_NetXtreme_Gigabit_Ethernet\"}[$interval]) + irate(wmi_net_packets_received_errors{instance=~\"$server\"}[$interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Received-下载",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "每秒磁盘读写",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(wmi_logical_disk_write_bytes_total{instance=~\"$server\", volume !~\"HarddiskVolume.+\"}[30s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Write {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "- irate(wmi_logical_disk_read_bytes_total{instance=~\"$server\", volume !~\"HarddiskVolume.+\"}[30s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Read {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "分区剩余空间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "wmi_logical_disk_free_bytes{instance=~\"$server\", volume !~\"HarddiskVolume.+\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "free {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Hard disk i/o ops total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(wmi_logical_disk_split_ios_total{instance=~\"$server\", volume !~\"HarddiskVolume.+\"}[30s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "i/o {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wmi_os_processes", "legendFormat": "Processes" }
   ]
  },
  {
   "title": "Services by state",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(wmi_service_state{instance=~\"$server\"}) by (state)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{state}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "system_threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "wmi_system_threads{instance=~\"$server\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "system_threads",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "System exception dispatches",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(wmi_system_exception_dispatches_total{instance=~\"$server\"}[$interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "exceptions",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}